package poo;

public class Main {
    public static void main(String[] args) {
        Smartphone smartphone = new Smartphone("Samsung","Galaxy S25",24,true);
        smartphone.ligar();
        smartphone.exibirInfo();
        smartphone.tirarFoto();
        System.out.println("----------------------------");
        Notebook notebook1 = new Notebook("Dell","Inspiron",16,true);
        notebook1.ligar();
        notebook1.exibirInfo();
        notebook1.compilarCodigo();
        System.out.println("----------------------------");
        Smartwatch smartwatch2 = new Smartwatch("Fitbit","VersaoX",100,true);
        smartwatch2.ligar();
        smartwatch2.exibirInfo();
        smartwatch2.contarPassos();
        System.out.println("----------------------------");
        TV tv3 = new TV("LG","OLED55",55.0,"4K");
        tv3.ligar();
        tv3.exibirInfo();
        tv3.mudarCanal();
        System.out.println("----------------------------");
        Desktop desktop4 = new Desktop("HP","Pavilion",2000,true);
        desktop4.ligar();
        desktop4.exibirInfo();
        desktop4.rodarJogo();
        System.out.println("----------------------------");
        Impressora impressora5 = new Impressora("Epson","EcoTank",80,true);
        impressora5.ligar();
        impressora5.exibirInfo();
        impressora5.imprimirDocumento();
        System.out.println("----------------------------");
        CaixaSom caixasom6 = new CaixaSom("JBL","Flip",30,true);
        caixasom6.ligar();
        caixasom6.exibirInfo();
        caixasom6.reproduzirAudio();
        System.out.println("----------------------------");
        Monitor monitor7 = new Monitor("Samsung","Odyssey",27.0,"1440p");
        monitor7.ligar();
        monitor7.exibirInfo();
        monitor7.ajustarBrilho();
        System.out.println("----------------------------");
        Projetor projetor8 = new Projetor("Epson","HomeProj",3000,true);
        projetor8.ligar();
        projetor8.exibirInfo();
        projetor8.projetarImagem();
        System.out.println("----------------------------");
        Drone drone9 = new Drone("DJI","Mini",120,true);
        drone9.ligar();
        drone9.exibirInfo();
        drone9.voar();
        System.out.println("----------------------------");
        ConsoleJogos consolejogos10 = new ConsoleJogos("Sony","PlayBox",1000,true);
        consolejogos10.ligar();
        consolejogos10.exibirInfo();
        consolejogos10.iniciarJogo();
        System.out.println("----------------------------");
        RefrigeradorSmart refrigeradorsmart11 = new RefrigeradorSmart("Brastemp","FrostFree",350,true);
        refrigeradorsmart11.ligar();
        refrigeradorsmart11.exibirInfo();
        refrigeradorsmart11.ajustarTemperatura();
        System.out.println("----------------------------");
        MicroondasSmart microondassmart12 = new MicroondasSmart("LG","MegaCook",1200,true);
        microondassmart12.ligar();
        microondassmart12.exibirInfo();
        microondassmart12.aquecer();
        System.out.println("----------------------------");
        ArCondicionado arcondicionado13 = new ArCondicionado("Samsung","WindFree",12000,true);
        arcondicionado13.ligar();
        arcondicionado13.exibirInfo();
        arcondicionado13.ligarResfriamento();
        System.out.println("----------------------------");
        MaquinaCafe maquinacafe14 = new MaquinaCafe("Nespresso","Dolce",20,true);
        maquinacafe14.ligar();
        maquinacafe14.exibirInfo();
        maquinacafe14.fazerCafe();
        System.out.println("----------------------------");
        AspiradorRobotico aspiradorrobotico15 = new AspiradorRobotico("iRobot","Roomba",90,true);
        aspiradorrobotico15.ligar();
        aspiradorrobotico15.exibirInfo();
        aspiradorrobotico15.limparCasa();
        System.out.println("----------------------------");
        CameraSeguranca cameraseguranca16 = new CameraSeguranca("Intelbras","Vision",12,true);
        cameraseguranca16.ligar();
        cameraseguranca16.exibirInfo();
        cameraseguranca16.gravar();
        System.out.println("----------------------------");
        RoteadorWiFi roteadorwifi17 = new RoteadorWiFi("TP-Link","AX3000",3000,4);
        roteadorwifi17.ligar();
        roteadorwifi17.exibirInfo();
        roteadorwifi17.reiniciarRede();
        System.out.println("----------------------------");
    }
}